controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

pdf_generator:
  path: "/generate-pdf"
  controller: App\Controller\PdfGeneratorController::generatePDF
  methods: ["GET"]
